module.exports = {
	name: 'aiuto',
	description: 'not helpful!',
	execute(message, args) {
		var facts = ['Mai senza daghi mosè!',
        'Non so cosa altro potresti fatti donare!',
        'Con daghi nel mazzo agli eventi puoi mette una carta a liv 6 max!',
        'Il nano sto a pensare pure!',
        'Fine settimana dopo le 24 di sabato chiede sempre epica!',
        'Gioca merda di cane!',
        'Italy squad siete?',
        'Con ninja al 4 farò un bordello, ora mi arriva sto a 4/8!',
        'Potenzia a liv 4 max craig super eroe quello che lancia il fulmine!',
        'vai con Timmy mosquito!',
        'Se sono queste le battaglie vanno a caso le battaglie ma manco ci partecipo!',
        'Sisi avoia!',
        'Si almeno per una volta questa lega d\'oro, sennò maggior parte sto a fa figure di merda!',
        'Usa randy birra!',
        'La leggendaria più comune è stan e randy birra. Anche l\'orso!',
        'Metti il pappagallo!',
        'Gioca kyle wi fi!',
        'Però a questo record non mi conviene!',
        'Potenzia l\'ascia!',
        'Usa trasformazione!',
        'Io lo spaccatutto lo metto anche togliere il restante energia al boss!',
        'Lo spaccatutto toglie 68!',
        'Free win anche moooooo!',
        'Inviate agli sviluppatori l\'applicazione per rivendere le carte a cartman per chi ne ha troppe!',
        'Sto a fa i pacchetti del cinese!',
        'Ho speso anche 50 per rifà i pacchetti!',
        'A me sempre stan mi becco quello!',
        'Io ora uso cupido al posto dei gemelli che mi fa un casino di danni!',
        'Metti i gemelli!',
        'Uso pedine con alta energia per distrarre tutti poi attacco con le pedine piccole!',
        'Candele e rosari da parte ora!',
        'Battaglie del cinese 0 le ho perse tutte!',
        'Io e kafka rispettiamo sempre le 8 ore :P',
        'Si ma non va bene sto server!',
        'Il gioco è rincoglionito!',
        'Questo free win mi sa che ha incasinato l\'online!',
        'Gioco ma c\'è problema marketing!',
        'Eheheh! Ci sta! E lo sai XD',
        'Uscite dal gioco e andate a fare la spesa che tra poco non ci sarà più da mangiare :O',
        'A Napoli fila per comprare da mangiare, ma devo vede qua da me domani. Qua la notte è tutto chiuso!',
        'Al Titanic che è successo? Se un aereo sta per cadere che fa la gente? Nn impazzisce?',
        'Eh io lo so ma la gente non se ne frega niente!',
        'Milano si è liberata del sud!',
        'Ha vinto Bossi!'];
        var fact = Math.floor(Math.random() * facts.length);
        message.channel.send(facts[fact]);
	},
};
